config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get :about, to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms' 

  get :signup, to: 'users#new'
  resources :users do 
    member do 
      get :following, :followers
    end
  end
  resources :dishes

  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  delete :logout, to: 'sessions#destroy'

  resources :relationships, only: [:create, :destroy]

  get :favorites, to: 'favorites#index'
  post   "favorites/:dish_id/create"  => "favorites#create"
  delete "favorites/:dish_id/destroy" => "favorites#destroy"

  resources :comments, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 5)
    end
  end

  def about
  end

  def terms
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "筋肉メシ図鑑とは？") %>

<body class="about">

<div id="menu">
    <div class="menu-content wrapper">
        <h1>筋肉メシ図鑑とは？</h1>
        <h2 class="page-title">簡単な操作でみんなの筋肉メシを共有できます！</h2>
        <p><a href="" class="button">新規登録はこちら</a></p>
       
        
    </div>
</div>
    <div class="wrapper-2">
    <h1>みんなの筋肉メシの作り方が学べる！</h1>
    <div class="grid">
        
        <div class="item big-box">
            <img src="assets/about1.jpg" alt="pics">
            <p><a href="http://localhost:3000/dishes/14">サーモンのグリル</a></p>
        </div>
        <div class="item">
            <img src="assets/about6.jpg" alt="pics">
            <p><a href="http://localhost:3000/dishes/12">プロテインシェイク</a></p>
        </div>
        <div class="item">
            <img src="assets/about3.jpg" alt="pics">
            <p><a href="http://localhost:3000/dishes/12">豆乳シリアル</a></p>
        </div>
        <div class="item">
            <img src="assets/about4.jpg" alt="pics">
            <p><a href="http://localhost:3000/dishes/11">鶏胸肉のステーキ</a></p>
        </div>
        <div class="item">
            <img src="assets/about2.jpg" alt="pics">
            <p>牛肉フィレステーキ</p>
        </div>
        <div class="item">
            <img src="assets/about6.jpg" alt="pics">
            <p>料理名</p>
        </div>
        <div class="item">
            <img src="assets/about8.jpg" alt="pics">
            <p>ヘルシーブレッド</p>
        </div>
        <div class="item">
            <img src="assets/about9.jpg" alt="pics">
            <p>低脂質ハンバーガー</p>
        </div>
        <div class="item">
            <img src="assets/about10.jpg" alt="pics">
            <p>ビタミンたっぷりベリーパフェ</p>
        </div>
     </div>   
    </div>

    </body>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="container">
  <div class="row">
    <div class="col-md-9">
    <h3>みんなの料理 (<%= @feed_items.count %>)</h3>
    <%= render 'shared/feed' %>
  </div>
  <div class="col-md-3">
    <p><%= link_to "新しい料理を作る", new_dish_path, class: "btn btn-primary btn-lg btn-record" %></p>
  </div>
  </div>
  </div>
<% else %>
<%= render 'shared/recruit_login' %>
<center>
    <h1>筋肉メシ図鑑へようこそ！</h1>
    <h2>あなたの料理を投稿しませんか？</h2>
    <p>今日のレシピ、もう迷わない！</p>
</center>
<% end %>

app/views/static_pages/terms.html.erb
<% provide(:title, "利用規約") %>
<h1>利用規約</h1>